# Generated by Django 4.2.4 on 2024-09-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejsapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LastPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('image', models.ImageField(upload_to='last')),
            ],
        ),
    ]
