# Generated by Django 4.2.4 on 2024-07-15 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ejsapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trainer',
            name='slug',
        ),
    ]
