# Generated by Django 4.2.4 on 2024-07-16 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejsapp', '0002_remove_trainer_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='name',
            field=models.CharField(max_length=250),
        ),
    ]
