# Generated by Django 4.2.4 on 2024-08-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejsapp', '0005_testimonial'),
    ]

    operations = [
        migrations.AddField(
            model_name='testimonial',
            name='profession',
            field=models.TextField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
