# Generated by Django 4.2.4 on 2024-08-12 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejsapp', '0009_mainphotos_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainersGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to='trainersgroup')),
            ],
        ),
    ]
