# Generated by Django 4.2.4 on 2024-08-26 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ejsapp', '0015_benefits'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryPhotos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name1', models.CharField(max_length=250)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('image8', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('name2', models.CharField(max_length=250)),
                ('image01', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('image02', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('image03', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('image04', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('image05', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('image06', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('image07', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('image08', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('name3', models.CharField(max_length=250)),
                ('image001', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('image002', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('image003', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('image004', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('image005', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('image006', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('image007', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('image008', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('name4', models.CharField(max_length=250)),
                ('image0001', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('image0002', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('image0003', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('image0004', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('image0005', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('image0006', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('image0007', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('image0008', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('name5', models.CharField(max_length=250)),
                ('image00001', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('image00002', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('image00003', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('image00004', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('image00005', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('image00006', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('image00007', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('image00008', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('name6', models.CharField(max_length=250)),
                ('image000001', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('image000002', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('image000003', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('image000004', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('image000005', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('image000006', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('image000007', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('image000008', models.ImageField(blank=True, null=True, upload_to='blog')),
            ],
        ),
        migrations.AlterField(
            model_name='benefits',
            name='description1',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='description10',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='description2',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='description3',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='description4',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='description5',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='description6',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='description7',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='description8',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='benefits',
            name='description9',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog'),
        ),
        migrations.AlterField(
            model_name='testimonial',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='testimonial'),
        ),
    ]
